baseURL: http://classicaplus.com
staticDir: static
publishDir: ./public
metaDataFormat: "yaml"
disableHugoGeneratorInject: true
disableKinds: [ "RSS" ]
sectionPagesMenu: main

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    weight: 2
    menu:
      main:
        - identifier: about
          name: About
          url: /about/
          weight: 1
        - identifier: team
          name: Team
          url: /team/
          weight: 2
        - identifier: events
          name: Events
          url: /events/
          weight: 3
        - identifier: media
          name: Media
          url: /media/
          weight: 4
  ru:
    languageName: Русский
    weight: 1
    menu:
      main:
        - identifier: about
          name: "О проекте"
          url: /about/
          weight: 1
        - identifier: team
          name: Участники
          url: /team/
          weight: 2
        - identifier: events
          name: События
          url: /events/
          weight: 3
        - identifier: media
          name: Медиа
          url: /media/
          weight: 4
