---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Team
- type: directory
  path: data/team
  label: data - Team
  create: all
  match: "*.yaml"
  new_doc_ext: yaml
  templates:
  - team-member
- type: directory
  path: content/team
  label: ru content - Team
  create: all
  match: "*.*.ru.md"
  new_doc_ext: ru.md
  templates:
  - content
- type: directory
  path: content/team
  label: en content - Team
  create: all
  match: "*.*.en.md"
  new_doc_ext: en.md
  templates:
  - content
- type: document
  path: content/team/_index.ru.md
  label: ru index - Team
- type: document
  path: content/team/_index.en.md
  label: en index - Team
- type: heading
  label: Composers and Works
- type: directory
  path: data/composers
  label: data - Composers
  create: all
  match: "*.yaml"
  new_doc_ext: yaml
  templates:
  - composer
- type: directory
  path: data/works
  label: data - Works
  create: all
  match: "**/*.yaml"
  new_doc_ext: yaml
  templates:
  - work
- type: heading
  label: Places and Events
- type: directory
  path: data/places
  label: data - Places
  create: all
  match: "**/*.yaml"
  new_doc_ext: yaml
  templates:
  - place
- type: directory
  path: data/events
  label: data - Events
  create: all
  match: "**/*.yaml"
  new_doc_ext: yaml
  templates:
  - event
- type: directory
  path: content/events
  label: ru content - Events
  create: all
  match: "**/*.ru.md"
  new_doc_ext: ru.md
  templates:
  - content
- type: directory
  path: content/events
  label: en content - Events
  create: all
  match: "**/*.en.md"
  new_doc_ext: en.md
  templates:
  - content
- type: heading
  label: Miscellaneous
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
upload_dir: static/resources/img
public_path: static/resources/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
